udo: required

os: linux

language: generic

services:
  - docker

before_install:
  - docker-compose -f docker/docker-compose.yml up -d

script:
  - docker-compose -f docker/docker-compose.yml exec node yarn install
  - docker-compose -f docker/docker-compose.yml exec node yarn test

after_success:
  - docker-compose -f docker/docker-compose.yml stop
  - docker-compose -f docker/docker-compose.yml down -v --remove-orphans