version: "2.2"
services:
  node:
    image: node:8
    container_name: node_rdm
    volumes:
      - ./..:/usr/local/rdm
    tty: true
    working_dir: /usr/local/rdm
    networks:
      - rdm_node

networks:
  rdm_node:
    driver: bridge